spring.application.name=Devops-2
spring.datasource.url=jdbc:mysql://localhost:3306/driverManage?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081